### ISSUE TITLE
include support for doc strings AVRO-2001

### ISSUE THREAD

**Issue by arron-green** [salsify/avro-patches#8]
Thanks for creating this gem!   This repo has been very useful rather than waiting for upstream patches to make it into avro.

I understand that this patch might not be needed when upstream avro is > 1.8.2. However, is it possible to include AVRO-2001 as part of this gem? I put a lot of effort to document fields in my schemas and it's a shame that they get stripped off when they make it into my schema registry

**Comment by tjwp** [comment]
@arron-green Just for background which schema registry are using and is there a particular client you're using to register schemas with it?

**Comment by arron-green** [comment]
@tjwp confluent schema registry using with avromatic/avro_turf client

**Comment by tjwp** [comment]
One way that I've preserved the original JSON for the schema is to wrap the `Avro::Schema` class to keep a copy of the original JSON. Then override the `#to_s` method to return the original JSON instead of re-serializing the schema.

When we did this we also replaced the `AvroTurf::SchemaStore` used by avromatic with a custom schema store that returned wrapped schema objects.

This guaranteed that everything in the original JSON, even formatting, is preserved.

**Comment by arron-green** [comment]
@tjwp that sounds reasonable.  i will attempt that and report back.  thanks for the tip!

**Comment by arron-green** [comment]
@tjwp does your approach support cases where schemas reference other schema/records within the schema directory? It seems like i'd have to override the `real_parse` implementation in order to get this to work.  maybe i'm missing something

**Comment by tjwp** [comment]
I don't think that was an issue for us because we were using the [avro-builder](https://github.com/salsify/avro-builder) DSL. So any references were resolved in the DSL resulting in a single schema file.

Our custom schema store didn't support resolving dependencies like the `AvroTurf` implementation  and didn't call `real_parse` directly, only `parse` for our custom schema class.

The custom schema class delegated to `Avro::Schema`, so the implementation was along the lines of:

```ruby
class JsonPreservingAvroSchema < DelegateClass(Avro::Schema)
  def self.parse(json)
    new(Avro::Schema.parse(json), json)
  end

  def initialize(schema, json)
    @json = json
    super(schema)
  end
 
  def to_s
    @json
  end
end
```

**Comment by arron-green** [comment]
i was able to get around this issue with your proposed solution.  I will close this as it's no longer an issue.
